### ISSUE TITLE
Interested in CodeIgniter version?

### ISSUE THREAD

**Issue by tgalopin** [komarserjio/notejam#28]
This repository is really useful. Thanks for your work!

I was thinking to propose a CodeIgniter version, however I don't know if it would be useful as the framework usage is slowly decreasing. Do you think it would be interesting?

**Comment by komarserjio** [comment]
Hey @tgalopin. Is there any progress or I can close this issue? :)

**Comment by tgalopin** [comment]
Sorry, I won't have time for this :/ .

**Comment by komarserjio** [comment]
No problems, thanks for reply.
