### ISSUE TITLE
Padrino Install / Start Error

### ISSUE THREAD

**Issue by alijaffar** [komarserjio/notejam#40]
No idea what's wrong. I got through the readme to bundle install, then I get the error 
from the terminal:

"Gem files will remain installed in /var/lib/gems/1.9.1/gems/do_sqlite3-0.10.14 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/do_sqlite3-0.10.14/ext/do_sqlite3/gem_make.out
root@zee-HP-Pavilion-Notebook-PC: /var/www/html/padrino/notejam# padrino start
padrino: command not found"

**Comment by komarserjio** [comment]
Hi @alijaffar. Thanks for the feedback, I will check.

**Comment by komarserjio** [comment]
Could you please give more details about your environment?

**Comment by alijaffar** [comment]
Ubuntu 14.04. I've never used ruby before, is that the problem perhaps?
