### ISSUE TITLE
POST should be used for signout

### ISSUE THREAD

**Issue by mvitz** [komarserjio/notejam#45]
In contribute.rst the action for signing out of the application is described as ```GET /signout/```. The verb here should be POST! Some browser/addons prefetch all GET links on a given page which leads to a signed out user on every request if signout is reachable via GET.

**Comment by komarserjio** [comment]
Hmm, valuable comment.
I agree, should be changed to POST.

**Comment by malkusch** [comment]
Oops. I involuntarily closed this issue with #66. You might want to reopen this, as it's not solved for other implementations.
