### ISSUE TITLE
Symfony: rewrite

### ISSUE THREAD

**Issue by aminemat** [komarserjio/notejam#49]
The Symfony app is outdated and needs to be rewritten according to the [best practices](http://symfony.com/doc/current/best_practices/index.html) and using the latest LTS version 2.8.

I can give it a go if you like.

**Comment by komarserjio** [comment]
Yeah, the symfony app is a bit outdated. I would appreciate your contribution :)

**Comment by aminemat** [comment]
sounds like a plan !

**Comment by komarserjio** [comment]
:+1: 
Let me know if any questions :)

**Comment by aminemat** [comment]
PR #51 is out there.

**Comment by komarserjio** [comment]
Wow, that was quick!
Give me some time to go through changes :)

**Comment by aminemat** [comment]
yeah I was kinda bored :-) take your time.
