### ISSUE TITLE
Java/Spring implementation

### ISSUE THREAD

**Issue by malkusch** [komarserjio/notejam#52]
I'd volunteer for a Spring (Java) implementation. Just give a feedback if this would be accepted here.

**Comment by komarserjio** [comment]
Oh yes. All the time I think about Java implementation, but due to lack of production experience with Java I would need to invest a lot of time in this. 
Currently I work on clojure/compojure implementation and have negotiation with a guy who willing to provide Scala/Play implementation.

It would be great if you could volunteer Java implementation, so next big release will be JVM oriented: Java + Scala + Clojure.

**Comment by malkusch** [comment]
Excellent I'm in with Java/Spring. I'll keep you updated about the progress within this ticket here.

**Comment by komarserjio** [comment]
Great! Let me know if I can help you somehow.

**Comment by malkusch** [comment]
> All implementations are SQLite based

Is this really a hard requirement? My current implementation would simply use an integrated in memory HSQLDB which would of course loose all its content when the application terminates. But I guess for demonstration purposes this is sufficient, isn't it?

**Comment by komarserjio** [comment]
I'm not sure 100%, but is not it just about changing JDBC driver?
I would say that SQLite is a hard requirement. A developer who tries a framework for the first time should not worry about DB specifics. SQLite seems to me as "least surprise" solution.

**Comment by malkusch** [comment]
Ok, I just want to be sure that we're on the same page. Spring Boot can run out of the box with some bundled data bases (H2, HSQL and Derby). I.e. the database comes with the package manager and just works automatically as in memory storage without any further configuration.

SQLite will need a lot more explicit configuration in that sample application.

**Comment by castaway** [comment]
Wouldn't it make more sense for it to be "least surprise for the platform"? That way you could just dictate that it should be a "simple, easily installed, local use database" or similar

**Comment by komarserjio** [comment]
I understand your point. And I think SQLite is simple enough and platform/frameowrk independent solution. Since all other implementations already use SQLite it makes it the preferred solution. Of course, critical problem like missing driver could force us to change database, but I'm pretty sure it's not the case with such advanced platform as Java.

**Comment by malkusch** [comment]
> is not it just about changing JDBC driver?

To be honest I never used SQLite in a JPA context. What I read now, it could become quiet a pain, as there seems to be [no SQLite dialect for hibernate](https://developer.jboss.org/wiki/SupportedDatabases2) (the default JPA implementation in Spring boot). So maybe I'll have to switch to another JPA implementation (e.g. EclipseLink). But for now I'll postpone the SQLite integration.

**Comment by komarserjio** [comment]
Ok, sure, if it is showstopper use java embedded database. Can it be persistent, not in-memory?

**Comment by malkusch** [comment]
> Can it be persistent, not in-memory?

Sure that can be easily configured. I'll add that.

The reason why SQLite is a pain in Java is that it's a native C library. Building Java software against such libraries is not the Java way as it puts a dependency on a binary on the platform.

**Comment by komarserjio** [comment]
I'm using SQLite for clojure/compojure implementation 
https://github.com/komarserjio/notejam/blob/compojure/compojure/notejam/project.clj#L10 and it works fine. That's why I though it should be easy for Java as well. 
As I understand the issue is about Hibernate ORM, not Java/JVM, right?

**Comment by malkusch** [comment]
There are two issues:

- SQLite is a C library. It just works fine for you, because the org.xerial/sqlite-jdbc includes native libraries for major OS and platforms. But if you're not on any supported platform that library falls back to a Java implementation of SQLite which might have a different feature set as the C library.

- Because of the first issue. SQLite doesn't have a big role in Java land. Therefore the dialect is not officially supported by ORM vendors. I.e. if I want to use the Hibernate ORM with SQLite. I'll have to implement the SQLite dialect for Hibernate. Though I guess there are some implementations out there already.

So I'm not saying it's not possible, but it introduces a lot of friction, so that I would post pone that topic to the very end.

**Comment by komarserjio** [comment]
Agreed.

**Comment by malkusch** [comment]
I have a question regarding the password recovery process. It is supposed to send an email. How do the other projects send that mail? Is there a known server which can be used? Or is it part of the configuration process for the user to define a mail server?

Doing the transport against the MX by the application itself is something what I really don't want to do. This topic is too broad and I, as a grey listing user, don't want to exclude myself by a cheap implementation.

**Comment by komarserjio** [comment]
Just send mail into a file. Usually frameworks support smth like `FileTransport`. No need to send real email.

**Comment by malkusch** [comment]
Hi, I have a further question regarding paging through the notes. The screen shots nor the plain html samples do have a note list with a page menu. As paging comes in Spring for free I'd like to include that as well. But before I invent a layout, does any of the other implementations have that so that I could copy the layout? I tried some and didn't find that. Having this in the html templates would even be better.

**Comment by komarserjio** [comment]
Hi @malkusch.
Pagination is not in the spec yet and not supported by the apps. Your app might be the first one with support of pagination :)

**Comment by komarserjio** [comment]
I will add pagination block to html templates.

**Comment by malkusch** [comment]
Thank you.

**Comment by komarserjio** [comment]
Pagination added https://github.com/komarserjio/notejam/commit/4c1b642afcb2b9b3eedb71f35b18e449463c3490

**Comment by komarserjio** [comment]
Few suggestions about implementation:
- 10 notes per page
- show pagination block only if more than 1 page
- use `page` GET parameter
- ordering (by name or date) should work for the whole collection, not just current page. So ordering always sets `page=1`
