### ISSUE TITLE
Symfony: Missing argument 1 for Doctrine\ORM\EntityRepository::find()

### ISSUE THREAD

**Issue by malkusch** [komarserjio/notejam#61]
1. Click on a existing pad, e.g. http://127.0.0.1:8000/pads/5/notes
2. Click on create new note, e.g. http://127.0.0.1:8000/notes/create?pad=5

I see this warning with PHP-5.6:
>  Warning: Missing argument 1 for Doctrine\ORM\EntityRepository::find(), called in /home/malkusch/workspace/oss/notejam/symfony/notejam/src/AppBundle/Controller/NoteController.php on line 75 and defined
500 Internal Server Error - ContextErrorException

**Comment by komarserjio** [comment]
@aminemat could you please take a look?

**Comment by aminemat** [comment]
Looking.

**Comment by aminemat** [comment]
good catch @malkusch, thanks for reporting this.
#62 should fix it.
