### ISSUE TITLE
I've failed to import schema.sql into MySQL DB

### ISSUE THREAD

**Issue by smartbos** [komarserjio/notejam#70]
I'm using MySQL 5.6.19.

I tried to import schema.sql but I failed with message below.

```
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AUTOINCREMENT NOT NULL,
    email VARCHAR(75) NOT NULL,
    password VARCHAR(128' at line 2
```

After I edit three of AUTOINCREMENT in schema.sql file to AUTO_INCREMENT, I was able to import it.

**Comment by komarserjio** [comment]
Hi @smartbos,

As you may see in the docs SQLite database is used, not MySQL.
But, of course, you are welcome to use any database if you want :)
